"""
Gradio UI for Research Copilot.

Two tabs:
  1. Chat   — run a query through the agent graph; show the reasoning trace.
  2. Evaluation — load eval_results/results.csv (produced by eval/run_eval.py)
                  and render the ablation table.

Run locally:
    python app.py
"""
from __future__ import annotations

import json
from pathlib import Path

import gradio as gr
import pandas as pd

from app.graph import build_graph

GRAPH = build_graph()
EVAL_RESULTS_PATH = Path("eval_results/results.csv")


def run_query(query: str) -> tuple[str, str]:
    """Run a query through the graph. Returns (answer, formatted_trace)."""
    if not query.strip():
        return "Please enter a question.", ""

    final_state = GRAPH.invoke({"query": query})
    answer = final_state.get("final_answer", "(no answer produced)")

    # Pretty-print the trace for the UI panel
    trace_lines = []
    for step in final_state.get("trace", []):
        trace_lines.append(f"### {step['agent'].upper()}")
        for k, v in step.items():
            if k == "agent":
                continue
            if isinstance(v, list) and len(v) > 5:
                v = f"{v[:5]} ... ({len(v)} total)"
            trace_lines.append(f"- **{k}**: {v}")
        trace_lines.append("")
    trace_md = "\n".join(trace_lines)

    return answer, trace_md


def load_eval_results() -> pd.DataFrame:
    if not EVAL_RESULTS_PATH.exists():
        return pd.DataFrame({
            "config": ["(no eval results yet — run `python -m eval.run_eval`)"],
        })
    return pd.read_csv(EVAL_RESULTS_PATH)


with gr.Blocks(title="Research Copilot") as demo:
    gr.Markdown(
        "# 🔬 Research Copilot\n"
        "An agentic RAG system over your PDF corpus. "
        "Ask multi-hop questions and watch four agents collaborate."
    )

    with gr.Tab("Chat"):
        query_in = gr.Textbox(
            label="Your question",
            placeholder="e.g., Compare attention mechanisms across these papers.",
            lines=2,
        )
        ask_btn = gr.Button("Ask", variant="primary")
        answer_out = gr.Markdown(label="Answer")
        with gr.Accordion("🧠 Reasoning trace", open=False):
            trace_out = gr.Markdown()
        ask_btn.click(run_query, inputs=query_in, outputs=[answer_out, trace_out])

    with gr.Tab("Evaluation"):
        gr.Markdown(
            "## Ablation results\n"
            "Generated by `python -m eval.run_eval`. "
            "Higher is better for faithfulness, answer_relevancy, context_precision."
        )
        eval_df = gr.Dataframe(value=load_eval_results(), interactive=False)
        refresh_btn = gr.Button("Refresh")
        refresh_btn.click(lambda: load_eval_results(), outputs=eval_df)


if __name__ == "__main__":
    demo.launch()
